services:
  - type: web
    name: telegram-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_ID
        value: your_telegram_api_id
      - key: API_HASH
        value: your_telegram_api_hash
      - key: PHONE_NUMBER
        value: +12345678901
